import { db } from "../src/utils/db.server";

type User = {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
};

type Account = {
  name: string;
  account_number: number | null;
  is_group: boolean | null;
  parent_account_name: string | null;
};

type Currency = {
  name: string;
  exchange_rate: number | null;
  selling_rate: number | null;
  buying_rate: number | null;
  min_selling_rate: number | null;
  max_buying_rate: number | null;
  currency_symbol: string;
};

async function seed() {
  console.log("Seeding the database...");
  await createUserData();
  await createCurrencyData();
  await createAccountsData();
  await db.settings.create({
    data:{
      name: "Company Currency",
      type: "String",
      value: "IQD"
    }
  })
}

seed();

async function createUserData() {
  await Promise.all(
    getUsers().map((user) => {
      return db.user.create({
        data: {
          firstName: user.firstName,
          lastName: user.lastName,
          email: user.email,
          password: user.password,
        },
      });
    })
  );
}

async function createCurrencyData() {
  await Promise.all(
    getCurrencies().map((currency) => {
      return db.currency.create({
        data: {
          name: currency.name,
          exchange_rate: currency.exchange_rate,
          selling_rate: currency.selling_rate,
          buying_rate: currency.buying_rate,
          min_selling_rate: currency.min_selling_rate,
          max_buying_rate: currency.max_buying_rate,
          currency_symbol: currency.currency_symbol,
        },
      });
    })
  );
}

async function createAccountsData() {
  const accounts = getAccounts();
  let counter = 1;

  for (const account of accounts) {
    const existingAccount = await db.account.findFirst({
      where: {
        name: account.name,
      },
    });

    if (!existingAccount) {
      await new Promise<void>((resolve) => {
        setTimeout(async () => {
          await db.account.create({
            data: {
              name: account.name,
              account_number: account.account_number,
              is_group: account.is_group,
              parent_account_name: account.parent_account_name,
            },
          });

          console.log(`Added account ${counter}/${accounts.length}`);
          counter++;

          resolve();
        }, 200); // Wait for 1 second (1000 milliseconds) before inserting the next account
      });
    } else {
      console.log(`Skipped account with duplicate name: ${account.name}`);
    }
  }
}

function getUsers(): Array<User> {
  return [
    {
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      password: "123456789",
    },
    {
      firstName: "Alice",
      lastName: "Smith",
      email: "alice.smith@example.com",
      password: "123456789",
    },
    {
      firstName: "Bob",
      lastName: "Johnson",
      email: "bob.johnson@example.com",
      password: "123456789",
    },
    {
      firstName: "Emily",
      lastName: "Davis",
      email: "emily.davis@example.com",
      password: "123456789",
    },
    {
      firstName: "Michael",
      lastName: "Brown",
      email: "michael.brown@example.com",
      password: "123456789",
    },
  ];
}

function getAccounts(): Array<Account> {
  return [
    {
      name: "الموجودات",
      account_number: 1,
      is_group: true,
      parent_account_name: null,
    },
    {
      name: "المطلوبات",
      account_number: 2,
      is_group: true,
      parent_account_name: null,
    },
    {
      name: "الاستخدامات",
      account_number: 3,
      is_group: true,
      parent_account_name: null,
    },
    {
      name: "الموارد",
      account_number: 4,
      is_group: true,
      parent_account_name: null,
    },
    {
      name: "الموجودات الثابتة ( رئيسي )",
      account_number: 11,
      is_group: true,
      parent_account_name: "الموجودات",
    },
    {
      name: "مشروعات تحت اتنفيذ",
      account_number: 12,
      is_group: true,
      parent_account_name: "الموجودات",
    },
    {
      name: "المخزون",
      account_number: 13,
      is_group: true,
      parent_account_name: "الموجودات",
    },
    {
      name: "القروض الممنوحة",
      account_number: 14,
      is_group: true,
      parent_account_name: "الموجودات",
    },
    {
      name: "الاستثمارات المالية",
      account_number: 15,
      is_group: true,
      parent_account_name: "الموجودات",
    },
    {
      name: "المدينون",
      account_number: 16,
      is_group: true,
      parent_account_name: "الموجودات",
    },
    {
      name: "النقود",
      account_number: 18,
      is_group: true,
      parent_account_name: "الموجودات",
    },
    {
      name: "متقابلة مدينة",
      account_number: 19,
      is_group: true,
      parent_account_name: "الموجودات",
    },
    {
      name: "راس المال",
      account_number: 21,
      is_group: true,
      parent_account_name: "المطلوبات",
    },
    {
      name: "الاحتياطيات",
      account_number: 22,
      is_group: true,
      parent_account_name: "المطلوبات",
    },
    {
      name: "التخصيصات",
      account_number: 23,
      is_group: true,
      parent_account_name: "المطلوبات",
    },
    {
      name: "قروض مستلمة",
      account_number: 24,
      is_group: true,
      parent_account_name: "المطلوبات",
    },
    {
      name: "المصارف الدائنة",
      account_number: 25,
      is_group: true,
      parent_account_name: "المطلوبات",
    },
    {
      name: "الدائنون",
      account_number: 26,
      is_group: true,
      parent_account_name: "المطلوبات",
    },
    {
      name: "متقابلة دائنة",
      account_number: 29,
      is_group: true,
      parent_account_name: "الدائنون",
    },
    {
      name: "رواتب واجور",
      account_number: 31,
      is_group: true,
      parent_account_name: "الاستخدامات",
    },
    {
      name: "المستلزمات السلعلية",
      account_number: 32,
      is_group: true,
      parent_account_name: "الاستخدامات",
    },
    {
      name: "المستلزمات الخدمية",
      account_number: 33,
      is_group: true,
      parent_account_name: "الاستخدامات",
    },
    {
      name: "مقاولات وخدمات",
      account_number: 34,
      is_group: true,
      parent_account_name: "الاستخدامات",
    },
    {
      name: "مشتريات بضائع بغرض البيع",
      account_number: 35,
      is_group: true,
      parent_account_name: "الاستخدامات",
    },
    {
      name: "الفوائد واستئجار الاراضي",
      account_number: 36,
      is_group: true,
      parent_account_name: "الاستخدامات",
    },
    {
      name: "الاندثار",
      account_number: 37,
      is_group: true,
      parent_account_name: "الاستخدامات",
    },
    {
      name: "المصروفات التحويلية",
      account_number: 38,
      is_group: true,
      parent_account_name: "الاستخدامات",
    },
    {
      name: "مصروفات أخرى",
      account_number: 39,
      is_group: true,
      parent_account_name: "المصروفات التحويلية",
    },
    {
      name: "ايراد النشاط السلعي",
      account_number: 41,
      is_group: true,
      parent_account_name: "الموارد",
    },
    {
      name: "ايراد النشاط التجاري",
      account_number: 42,
      is_group: true,
      parent_account_name: "الموارد",
    },
    {
      name: "ايراد النشاط الخدمي",
      account_number: 43,
      is_group: true,
      parent_account_name: "الموارد",
    },
    {
      name: "ايراد الشتغيل للغير",
      account_number: 44,
      is_group: true,
      parent_account_name: "الموارد",
    },
    {
      name: "كلفة الموجودات المصنعة داخليا",
      account_number: 45,
      is_group: true,
      parent_account_name: "الموارد",
    },
    {
      name: "فوائد وايجارات الأراضي",
      account_number: 46,
      is_group: true,
      parent_account_name: "الموارد",
    },
    {
      name: "الإعانات",
      account_number: 47,
      is_group: true,
      parent_account_name: "الموارد",
    },
    {
      name: "الإيرادات التحويلية",
      account_number: 48,
      is_group: true,
      parent_account_name: "الموارد",
    },
    {
      name: "ايرادات عرضية رئيسي",
      account_number: 49,
      is_group: true,
      parent_account_name: "الموارد",
    },
    {
      name: "اراضي",
      account_number: 111,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "مباني وانشاءات",
      account_number: 112,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "الآت ومعدات",
      account_number: 113,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "وسائل نقل وأنتقال",
      account_number: 114,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "عدد وقوالب",
      account_number: 115,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "نفقات ايراديه مؤجله",
      account_number: 118,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "أراضي",
      account_number: 121,
      is_group: true,
      parent_account_name: "مشروعات تحت اتنفيذ",
    },
    {
      name: "الآت ومعدات",
      account_number: 123,
      is_group: true,
      parent_account_name: "مشروعات تحت اتنفيذ",
    },
    {
      name: "مخزون الخامات والمواد الأولية",
      account_number: 131,
      is_group: true,
      parent_account_name: "المخزون",
    },
    {
      name: "مخزون الوقود والزيوت",
      account_number: 132,
      is_group: true,
      parent_account_name: "المخزون",
    },
    {
      name: "مخزون الادوات الاحتياطية",
      account_number: 133,
      is_group: true,
      parent_account_name: "المخزون",
    },
    {
      name: "مخزون مواد التعبئة والتغليف",
      account_number: 134,
      is_group: true,
      parent_account_name: "المخزون",
    },
    {
      name: "مخزون المتنوعات",
      account_number: 135,
      is_group: true,
      parent_account_name: "المخزون",
    },
    {
      name: "مخزون الإنتاج",
      account_number: 136,
      is_group: true,
      parent_account_name: "المخزون",
    },
    {
      name: "مخزون البضائع بغرض البيع",
      account_number: 137,
      is_group: true,
      parent_account_name: "المخزون",
    },
    {
      name: "اعتمادات مستندية لشراء مواد",
      account_number: 138,
      is_group: true,
      parent_account_name: "المخزون",
    },
    {
      name: "مخزون المواد الأخرى",
      account_number: 139,
      is_group: true,
      parent_account_name: "المخزون",
    },
    {
      name: "قروض ممنوحة طويلة الاجل",
      account_number: 141,
      is_group: true,
      parent_account_name: "القروض الممنوحة",
    },
    {
      name: "قروض ممنوحة قصيرة الاجل",
      account_number: 142,
      is_group: true,
      parent_account_name: "القروض الممنوحة",
    },
    {
      name: "استثمارات طويلة الاجل",
      account_number: 151,
      is_group: true,
      parent_account_name: "الاستثمارات المالية",
    },
    {
      name: "استثمارات قصيرة الاجل",
      account_number: 152,
      is_group: true,
      parent_account_name: "الاستثمارات المالية",
    },
    {
      name: "مدينون تجاريون",
      account_number: 161,
      is_group: true,
      parent_account_name: "المدينون",
    },
    {
      name: "أوراق قبض",
      account_number: 162,
      is_group: true,
      parent_account_name: "المدينون",
    },
    {
      name: "حسابات جارية مدينة",
      account_number: 163,
      is_group: true,
      parent_account_name: "المدينون",
    },
    {
      name: "سلف التعهدات",
      account_number: 164,
      is_group: true,
      parent_account_name: "المدينون",
    },
    {
      name: "مدينو نشاط غير جاري",
      account_number: 165,
      is_group: true,
      parent_account_name: "المدينون",
    },
    {
      name: "حسابات مدينة متنوعة",
      account_number: 166,
      is_group: true,
      parent_account_name: "المدينون",
    },
    {
      name: "سلف",
      account_number: 167,
      is_group: true,
      parent_account_name: "المدينون",
    },
    {
      name: "نقدية بالصندوق",
      account_number: 181,
      is_group: true,
      parent_account_name: "النقود",
    },
    {
      name: "سلف مستديمة",
      account_number: 182,
      is_group: true,
      parent_account_name: "النقود",
    },
    {
      name: "نقدية لدى المصارف",
      account_number: 183,
      is_group: true,
      parent_account_name: "النقود",
    },
    {
      name: "نقدية لدى الخزائن",
      account_number: 184,
      is_group: true,
      parent_account_name: "النقود",
    },
    {
      name: "صكوك وحوالات",
      account_number: 185,
      is_group: true,
      parent_account_name: "النقود",
    },
    {
      name: "رأس المال الاسمي المدفوع",
      account_number: 211,
      is_group: true,
      parent_account_name: "راس المال",
    },
    {
      name: "احتياطي راسمالية",
      account_number: 221,
      is_group: true,
      parent_account_name: "الاحتياطيات",
    },
    {
      name: "احتياطي عام",
      account_number: 222,
      is_group: true,
      parent_account_name: "الاحتياطيات",
    },
    {
      name: "احتياطي قانوني",
      account_number: 223,
      is_group: true,
      parent_account_name: "الاحتياطيات",
    },
    {
      name: "الفائض المتراكم",
      account_number: 224,
      is_group: true,
      parent_account_name: "الاحتياطيات",
    },
    {
      name: "العجز المتراكم",
      account_number: 225,
      is_group: true,
      parent_account_name: "الاحتياطيات",
    },
    {
      name: "مخصص الاندثار المتراكم",
      account_number: 231,
      is_group: true,
      parent_account_name: "التخصيصات",
    },
    {
      name: "مخصص الديون المشكوك في تحصيلها",
      account_number: 232,
      is_group: true,
      parent_account_name: "التخصيصات",
    },
    {
      name: "مخصص مصروفات الشراء",
      account_number: 234,
      is_group: true,
      parent_account_name: "التخصيصات",
    },
    {
      name: "تخصيصات قصيرة الأجل",
      account_number: 235,
      is_group: true,
      parent_account_name: "التخصيصات",
    },
    {
      name: "تخصيصات ضريبة الدخل",
      account_number: 236,
      is_group: true,
      parent_account_name: "التخصيصات",
    },
    {
      name: "تخصيصات دائرة الضمان",
      account_number: 237,
      is_group: true,
      parent_account_name: "التخصيصات",
    },
    {
      name: "قروض مستلمة طويلة الأجل",
      account_number: 241,
      is_group: true,
      parent_account_name: "قروض مستلمة",
    },
    {
      name: "قروض مستلمة قصيرة الأجل",
      account_number: 242,
      is_group: true,
      parent_account_name: "قروض مستلمة",
    },
    {
      name: "جاري مكشوف 1",
      account_number: 251,
      is_group: true,
      parent_account_name: "المصارف الدائنة",
    },
    {
      name: "جاري مكشوف 2",
      account_number: 252,
      is_group: true,
      parent_account_name: "المصارف الدائنة",
    },
    {
      name: "المجهزون",
      account_number: 261,
      is_group: true,
      parent_account_name: "الدائنون",
    },
    {
      name: "أوراق دفع",
      account_number: 262,
      is_group: true,
      parent_account_name: "الدائنون",
    },
    {
      name: "حسابات جارية دائنة",
      account_number: 263,
      is_group: true,
      parent_account_name: "الدائنون",
    },
    {
      name: "حسابات التعهدات",
      account_number: 264,
      is_group: true,
      parent_account_name: "الدائنون",
    },
    {
      name: "دائنو نشاط غير جاري",
      account_number: 265,
      is_group: true,
      parent_account_name: "الدائنون",
    },
    {
      name: "دائرة الضمان الاجتماعي",
      account_number: 266,
      is_group: true,
      parent_account_name: "الدائنون",
    },
    {
      name: "استقطاعات لحساب الغير",
      account_number: 267,
      is_group: true,
      parent_account_name: "الدائنون",
    },
    {
      name: "دائنو توزيع الارباح",
      account_number: 268,
      is_group: true,
      parent_account_name: "الدائنون",
    },
    {
      name: "موقوفات متنوعة / فتح رصيد الصندوق",
      account_number: 269,
      is_group: true,
      parent_account_name: "الدائنون",
    },
    {
      name: "حساب النشاط الجاري",
      account_number: 281,
      is_group: true,
      parent_account_name: "الدائنون",
    },
    {
      name: "حسابات النتيجة الدائنة",
      account_number: 294,
      is_group: true,
      parent_account_name: "متقابلة دائنة",
    },
    {
      name: "رواتب واجور الموظفين",
      account_number: 311,
      is_group: true,
      parent_account_name: "رواتب واجور",
    },
    {
      name: "رواتب غير العراقيين",
      account_number: 313,
      is_group: true,
      parent_account_name: "رواتب واجور",
    },
    {
      name: "ضمان اجتماعي للموظفين",
      account_number: 314,
      is_group: true,
      parent_account_name: "رواتب واجور",
    },
    {
      name: "ضمان اجتماعي للعمال",
      account_number: 315,
      is_group: true,
      parent_account_name: "رواتب واجور",
    },
    {
      name: "ضمان اجتماعي لغير العراقيين",
      account_number: 316,
      is_group: true,
      parent_account_name: "رواتب واجور",
    },
    {
      name: "خامات ومواد أولية",
      account_number: 321,
      is_group: true,
      parent_account_name: "المستلزمات السلعلية",
    },
    {
      name: "وقود وزيوت",
      account_number: 322,
      is_group: true,
      parent_account_name: "المستلزمات السلعلية",
    },
    {
      name: "الادوات الاحتياطية",
      account_number: 323,
      is_group: true,
      parent_account_name: "المستلزمات السلعلية",
    },
    {
      name: "مواد التعبئة والتغليف",
      account_number: 324,
      is_group: true,
      parent_account_name: "المستلزمات السلعلية",
    },
    {
      name: "المتنوعات",
      account_number: 325,
      is_group: true,
      parent_account_name: "المستلزمات السلعلية",
    },
    {
      name: "تجهيزات العاملين",
      account_number: 326,
      is_group: true,
      parent_account_name: "المستلزمات السلعلية",
    },
    {
      name: "المياه والكهرباء",
      account_number: 327,
      is_group: true,
      parent_account_name: "المستلزمات السلعلية",
    },
    {
      name: "خدمات الصيانة",
      account_number: 331,
      is_group: true,
      parent_account_name: "المستلزمات الخدمية",
    },
    {
      name: "خدمات ابحاث وتجارب",
      account_number: 332,
      is_group: true,
      parent_account_name: "المستلزمات الخدمية",
    },
    {
      name: "دعاية وطبع وضيافة",
      account_number: 333,
      is_group: true,
      parent_account_name: "المستلزمات الخدمية",
    },
    {
      name: "نقل وايفاد واتصالات",
      account_number: 334,
      is_group: true,
      parent_account_name: "المستلزمات الخدمية",
    },
    {
      name: "استئجار موجودات ثابتة",
      account_number: 335,
      is_group: true,
      parent_account_name: "المستلزمات الخدمية",
    },
    {
      name: "مصروفات خدمية متنوعة",
      account_number: 336,
      is_group: true,
      parent_account_name: "المستلزمات الخدمية",
    },
    {
      name: "مقاولات قانونية",
      account_number: 341,
      is_group: false,
      parent_account_name: "مقاولات وخدمات",
    },
    {
      name: "خدمات التشغيل",
      account_number: 342,
      is_group: false,
      parent_account_name: "مقاولات وخدمات",
    },
    {
      name: "مشتريات بضائع بغرض البيع محلية",
      account_number: 351,
      is_group: false,
      parent_account_name: "مشتريات بضائع بغرض البيع",
    },
    {
      name: "مشتريات بضائع بغرض البيع مستوردة",
      account_number: 352,
      is_group: false,
      parent_account_name: "مشتريات بضائع بغرض البيع",
    },
    {
      name: "فوائد مدينة",
      account_number: 361,
      is_group: false,
      parent_account_name: "الفوائد واستئجار الاراضي",
    },
    {
      name: "ايجارات الاراضي",
      account_number: 362,
      is_group: false,
      parent_account_name: "الفوائد واستئجار الاراضي",
    },
    {
      name: "اندثار مباني وانشاءات وطرق",
      account_number: 372,
      is_group: false,
      parent_account_name: "الاندثار",
    },
    {
      name: "اندثار الات ومعدات",
      account_number: 373,
      is_group: false,
      parent_account_name: "الاندثار",
    },
    {
      name: "اندثار وسائل نقل وانتقال",
      account_number: 374,
      is_group: false,
      parent_account_name: "الاندثار",
    },
    {
      name: "اندثار عدد وقوالب",
      account_number: 375,
      is_group: false,
      parent_account_name: "الاندثار",
    },
    {
      name: "اندثار اثاث",
      account_number: 376,
      is_group: false,
      parent_account_name: "الاندثار",
    },
    {
      name: "اهلاك نباتات وحيوانات",
      account_number: 377,
      is_group: false,
      parent_account_name: "الاندثار",
    },
    {
      name: "اطفاء نفقات تاسيس",
      account_number: 378,
      is_group: false,
      parent_account_name: "الاندثار",
    },
    {
      name: "نفقات التقاعد والضمان الاجتماعي",
      account_number: 381,
      is_group: true,
      parent_account_name: "المصروفات التحويلية",
    },
    {
      name: "المساهمة في نفقات الوحدات المركزية او التابعه",
      account_number: 382,
      is_group: true,
      parent_account_name: "المصروفات التحويلية",
    },
    {
      name: "مصروقات تحويلية متنوعة",
      account_number: 383,
      is_group: true,
      parent_account_name: "المصروفات التحويلية",
    },
    {
      name: "ضرائب ورسوم رئيسي",
      account_number: 384,
      is_group: true,
      parent_account_name: "المصروفات التحويلية",
    },
    {
      name: "اعانات",
      account_number: 385,
      is_group: true,
      parent_account_name: "المصروفات التحويلية",
    },
    {
      name: "مصروفات سنوات سابقة",
      account_number: 391,
      is_group: false,
      parent_account_name: "مصروفات أخرى",
    },
    {
      name: "مصروفات عرضية",
      account_number: 392,
      is_group: false,
      parent_account_name: "مصروفات أخرى",
    },
    {
      name: "خسائر رأسمالية",
      account_number: 393,
      is_group: false,
      parent_account_name: "مصروفات أخرى",
    },
    {
      name: "إيراد نشاط الصناعات الاستخراجية",
      account_number: 411,
      is_group: false,
      parent_account_name: "ايراد النشاط السلعي",
    },
    {
      name: "إيراد نشاط الصناعات التحويلية",
      account_number: 412,
      is_group: false,
      parent_account_name: "ايراد النشاط السلعي",
    },
    {
      name: "إيراد نشاط التشييد",
      account_number: 413,
      is_group: false,
      parent_account_name: "ايراد النشاط السلعي",
    },
    {
      name: "ايراد نشاط الانتاج النباتي",
      account_number: 414,
      is_group: false,
      parent_account_name: "ايراد النشاط السلعي",
    },
    {
      name: "ايراد نشاط الانتاج الحيواني",
      account_number: 415,
      is_group: false,
      parent_account_name: "ايراد النشاط السلعي",
    },
    {
      name: "ايراد ماء وكهرباء",
      account_number: 416,
      is_group: false,
      parent_account_name: "ايراد النشاط السلعي",
    },
    {
      name: "صافي مبيعات بضائع بغرض البيع",
      account_number: 421,
      is_group: false,
      parent_account_name: "ايراد النشاط التجاري",
    },
    {
      name: "تغير مخازن بضائع بغرض البيع",
      account_number: 422,
      is_group: false,
      parent_account_name: "ايراد النشاط التجاري",
    },
    {
      name: "عمولة مستلمة",
      account_number: 423,
      is_group: false,
      parent_account_name: "ايراد النشاط التجاري",
    },
    {
      name: "ايراد الفندقة والسياحة",
      account_number: 424,
      is_group: false,
      parent_account_name: "ايراد النشاط التجاري",
    },
    {
      name: "ايرادات متنوعه",
      account_number: 425,
      is_group: false,
      parent_account_name: "ايراد النشاط التجاري",
    },
    {
      name: "ايراد خدمات النقل",
      account_number: 431,
      is_group: false,
      parent_account_name: "ايراد النشاط الخدمي",
    },
    {
      name: "ايراد خدمات الاتصالات",
      account_number: 432,
      is_group: false,
      parent_account_name: "ايراد النشاط الخدمي",
    },
    {
      name: "ايراد خدمات الصيانة والتصليح",
      account_number: 433,
      is_group: false,
      parent_account_name: "ايراد النشاط الخدمي",
    },
    {
      name: "ايراد خدمات استشارية وفنية",
      account_number: 434,
      is_group: false,
      parent_account_name: "ايراد النشاط الخدمي",
    },
    {
      name: "ايراد خدمات اجتماعية",
      account_number: 435,
      is_group: false,
      parent_account_name: "ايراد النشاط الخدمي",
    },
    {
      name: "ايراد انتساب واشتراك",
      account_number: 436,
      is_group: false,
      parent_account_name: "ايراد النشاط الخدمي",
    },
    {
      name: "ايراد خدمات متنوعة",
      account_number: 437,
      is_group: false,
      parent_account_name: "ايراد النشاط الخدمي",
    },
    {
      name: "ايجار موجودات ثابتة",
      account_number: 438,
      is_group: false,
      parent_account_name: "ايراد النشاط الخدمي",
    },
    {
      name: "ايراد النشاط للغير",
      account_number: 441,
      is_group: false,
      parent_account_name: "ايراد الشتغيل للغير",
    },
    {
      name: "كلفة الموجودات الثابتة المصنعة",
      account_number: 451,
      is_group: false,
      parent_account_name: "كلفة الموجودات المصنعة داخليا",
    },
    {
      name: "كلفة الادوات الاحتياطية المصنعة",
      account_number: 452,
      is_group: false,
      parent_account_name: "كلفة الموجودات المصنعة داخليا",
    },
    {
      name: "كلفة مواد التعبئة المتداولة المصنعة",
      account_number: 453,
      is_group: false,
      parent_account_name: "كلفة الموجودات المصنعة داخليا",
    },
    {
      name: "ايرادات مدينة",
      account_number: 461,
      is_group: false,
      parent_account_name: "فوائد وايجارات الأراضي",
    },
    {
      name: "ايراد ايجارات الاراضي",
      account_number: 462,
      is_group: false,
      parent_account_name: "فوائد وايجارات الأراضي",
    },
    {
      name: "ايرادات الاستثمارات المالية",
      account_number: 463,
      is_group: false,
      parent_account_name: "فوائد وايجارات الأراضي",
    },
    {
      name: "اعانات سلع مستوردة",
      account_number: 471,
      is_group: false,
      parent_account_name: "الإعانات",
    },
    {
      name: "اعانات انتاج محلي",
      account_number: 472,
      is_group: false,
      parent_account_name: "الإعانات",
    },
    {
      name: "اعانات تصدير",
      account_number: 473,
      is_group: false,
      parent_account_name: "الإعانات",
    },
    {
      name: "اعانات اخرى",
      account_number: 474,
      is_group: false,
      parent_account_name: "الإعانات",
    },
    {
      name: "ايرادات سنوات سابقة",
      account_number: 491,
      is_group: false,
      parent_account_name: "ايرادات عرضية رئيسي",
    },
    {
      name: "ايرادات عرضية",
      account_number: 492,
      is_group: false,
      parent_account_name: "ايرادات عرضية رئيسي",
    },
    {
      name: "ايرادات رأسمالية",
      account_number: 493,
      is_group: false,
      parent_account_name: "ايرادات عرضية رئيسي",
    },
    {
      name: "اراضي بناء",
      account_number: 1112,
      is_group: true,
      parent_account_name: "اراضي",
    },
    {
      name: "اراضي فضاء",
      account_number: 1113,
      is_group: true,
      parent_account_name: "اراضي",
    },
    {
      name: "مباني",
      account_number: 1121,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "مخازن وخزانات وسايلوات",
      account_number: 1122,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "منشأت سكنية",
      account_number: 1123,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "سدود وقنوات",
      account_number: 1125,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "منشأت عائمة",
      account_number: 1126,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "طرق وجسور",
      account_number: 1127,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "وسائل النقل بالسكك الحديدية",
      account_number: 1142,
      is_group: true,
      parent_account_name: "وسائل نقل وأنتقال",
    },
    {
      name: "وسائل النقل النهري",
      account_number: 1143,
      is_group: true,
      parent_account_name: "وسائل نقل وأنتقال",
    },
    {
      name: "وسائل النقل البحري",
      account_number: 1144,
      is_group: true,
      parent_account_name: "وسائل نقل وأنتقال",
    },
    {
      name: "وسائل النقل الجوي",
      account_number: 1145,
      is_group: true,
      parent_account_name: "وسائل نقل وأنتقال",
    },
    {
      name: "خطوط انابيب النفط والغاز",
      account_number: 1146,
      is_group: true,
      parent_account_name: "وسائل نقل وأنتقال",
    },
    {
      name: "عدد",
      account_number: 1151,
      is_group: true,
      parent_account_name: "عدد وقوالب",
    },
    {
      name: "قوالب",
      account_number: 1152,
      is_group: true,
      parent_account_name: "عدد وقوالب",
    },
    {
      name: "خيم وجوادر",
      account_number: 1153,
      is_group: true,
      parent_account_name: "عدد وقوالب",
    },
    {
      name: "اثاث واجهزة مكاتب",
      account_number: 1161,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "اجهزة تكييف وتبريد",
      account_number: 1162,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "حاسبات الكترونية",
      account_number: 1163,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "الات حاسبة وكاتبة واستنساخ",
      account_number: 1164,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "ادوات وأجهزة مكاتب",
      account_number: 1165,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "ستائر ومفروشات",
      account_number: 1166,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "كتب ومراجع علمية",
      account_number: 1167,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "نباتات",
      account_number: 1171,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "حيوانات",
      account_number: 1172,
      is_group: true,
      parent_account_name: "الموجودات الثابتة ( رئيسي )",
    },
    {
      name: "نفقات التأسيس",
      account_number: 1181,
      is_group: true,
      parent_account_name: "نفقات ايراديه مؤجله",
    },
    {
      name: "نفقات قبل التشغيل",
      account_number: 1182,
      is_group: true,
      parent_account_name: "نفقات ايراديه مؤجله",
    },
    {
      name: "نفقات استكشاف ومسح",
      account_number: 1183,
      is_group: true,
      parent_account_name: "نفقات ايراديه مؤجله",
    },
    {
      name: "نفقات ابحاث وتجارب",
      account_number: 1184,
      is_group: true,
      parent_account_name: "نفقات ايراديه مؤجله",
    },
    {
      name: "موجودات ثابتة ومعنوية",
      account_number: 1185,
      is_group: true,
      parent_account_name: "نفقات ايراديه مؤجله",
    },
    {
      name: "ديكورات وتركيبات وقواطع",
      account_number: 1186,
      is_group: true,
      parent_account_name: "نفقات ايراديه مؤجله",
    },
    {
      name: "نفقات مؤجلة متنوعة",
      account_number: 1187,
      is_group: true,
      parent_account_name: "نفقات ايراديه مؤجله",
    },
    {
      name: "مخزون مواد التعبئة والتغليف المستهلكة",
      account_number: 1341,
      is_group: true,
      parent_account_name: "مخزون مواد التعبئة والتغليف",
    },
    {
      name: "مخزون مواد التعبئة المتداولة",
      account_number: 1342,
      is_group: true,
      parent_account_name: "مخزون مواد التعبئة والتغليف",
    },
    {
      name: "مخزون اللوازم والمهمات",
      account_number: 1351,
      is_group: true,
      parent_account_name: "مخزون المتنوعات",
    },
    {
      name: "مخزون القرطاسية",
      account_number: 1352,
      is_group: true,
      parent_account_name: "مخزون المتنوعات",
    },
    {
      name: "مخزون الكتب التعليمية",
      account_number: 1353,
      is_group: true,
      parent_account_name: "مخزون المتنوعات",
    },
    {
      name: "مخزون المخلفات والمستهلكات",
      account_number: 1354,
      is_group: true,
      parent_account_name: "مخزون المتنوعات",
    },
    {
      name: "مخزون تجهيزات العاملين",
      account_number: 1355,
      is_group: true,
      parent_account_name: "مخزون المتنوعات",
    },
    {
      name: "مخزون الانتاج التام",
      account_number: 1361,
      is_group: true,
      parent_account_name: "مخزون الإنتاج",
    },
    {
      name: "مخزون الانتاج غير التام والاعمال تحت التنفيذ",
      account_number: 1362,
      is_group: true,
      parent_account_name: "مخزون الإنتاج",
    },
    {
      name: "اعتمادات مستندية لحساب المنشأة",
      account_number: 1381,
      is_group: true,
      parent_account_name: "اعتمادات مستندية لشراء مواد",
    },
    {
      name: "اعتمادات مستندية لحساب الغير",
      account_number: 1382,
      is_group: true,
      parent_account_name: "اعتمادات مستندية لشراء مواد",
    },
    {
      name: "بضائع لدى الغير",
      account_number: 1391,
      is_group: true,
      parent_account_name: "مخزون المواد الأخرى",
    },
    {
      name: "قروض ممنوحة طويلة الاجل للقطاع الاشتراكي",
      account_number: 1411,
      is_group: true,
      parent_account_name: "قروض ممنوحة طويلة الاجل",
    },
    {
      name: "قروض ممنوحة طويلة الاجل للقطاع التعاوني",
      account_number: 1412,
      is_group: true,
      parent_account_name: "قروض ممنوحة طويلة الاجل",
    },
    {
      name: "قروض ممنوحة طويلة الاجل للقطاع المختلط",
      account_number: 1413,
      is_group: true,
      parent_account_name: "قروض ممنوحة طويلة الاجل",
    },
    {
      name: "قروض ممنوحة طويلة الاجل للقطاع الخاص",
      account_number: 1414,
      is_group: true,
      parent_account_name: "قروض ممنوحة طويلة الاجل",
    },
    {
      name: "قروض ممنوحة طويلة الاجل للعالم الخارجي",
      account_number: 1415,
      is_group: true,
      parent_account_name: "قروض ممنوحة طويلة الاجل",
    },
    {
      name: "قروض ممنوحة قصيرة الاجل للقطاع الاشتراكي",
      account_number: 1421,
      is_group: true,
      parent_account_name: "قروض ممنوحة قصيرة الاجل",
    },
    {
      name: "قروض ممنوحة قصيرة الاجل للقطاع التعاوني",
      account_number: 1422,
      is_group: true,
      parent_account_name: "قروض ممنوحة قصيرة الاجل",
    },
    {
      name: "قروض ممنوحة قصيرة الاجل للقطاع المختلط",
      account_number: 1423,
      is_group: true,
      parent_account_name: "قروض ممنوحة قصيرة الاجل",
    },
    {
      name: "قروض ممنوحة قصيرة الاجل للقطاع الخاص",
      account_number: 1424,
      is_group: true,
      parent_account_name: "قروض ممنوحة قصيرة الاجل",
    },
    {
      name: "قروض ممنوحة قصيرة الاجل للعالم الخارجي",
      account_number: 1425,
      is_group: true,
      parent_account_name: "قروض ممنوحة قصيرة الاجل",
    },
    {
      name: "استثمارات طويلة في القطاع الاشتراكي",
      account_number: 1511,
      is_group: true,
      parent_account_name: "استثمارات طويلة الاجل",
    },
    {
      name: "استثمارات طويلة في القطاع التعاوني",
      account_number: 1512,
      is_group: true,
      parent_account_name: "استثمارات طويلة الاجل",
    },
    {
      name: "استثمارات طويلة في القطاع المختلط",
      account_number: 1513,
      is_group: true,
      parent_account_name: "استثمارات طويلة الاجل",
    },
    {
      name: "استثمارات طويلة في القطاع الخاص",
      account_number: 1514,
      is_group: true,
      parent_account_name: "استثمارات طويلة الاجل",
    },
    {
      name: "استثمارات طويلة في العالم الخارجي",
      account_number: 1515,
      is_group: true,
      parent_account_name: "استثمارات طويلة الاجل",
    },
    {
      name: "استثمارات قصيرة في القطاع الاشتراكي",
      account_number: 1521,
      is_group: true,
      parent_account_name: "استثمارات قصيرة الاجل",
    },
    {
      name: "استثمارات قصيرة في القطاع التعاوني",
      account_number: 1522,
      is_group: true,
      parent_account_name: "استثمارات قصيرة الاجل",
    },
    {
      name: "استثمارات قصيرة في القطاع المختلط",
      account_number: 1523,
      is_group: true,
      parent_account_name: "استثمارات قصيرة الاجل",
    },
    {
      name: "استثمارات قصيرة في القطاع الخاص",
      account_number: 1524,
      is_group: true,
      parent_account_name: "استثمارات قصيرة الاجل",
    },
    {
      name: "استثمارات قصيرة في العالم الخارجي",
      account_number: 1525,
      is_group: true,
      parent_account_name: "استثمارات قصيرة الاجل",
    },
    {
      name: "عملاء قطاع اشتراكي",
      account_number: 1611,
      is_group: true,
      parent_account_name: "مدينون تجاريون",
    },
    {
      name: "عملاء قطاع تعاوني",
      account_number: 1612,
      is_group: true,
      parent_account_name: "مدينون تجاريون",
    },
    {
      name: "عملاء قطاع مختلط",
      account_number: 1613,
      is_group: true,
      parent_account_name: "مدينون تجاريون",
    },
    {
      name: "عملاء قطاع خاص",
      account_number: 1614,
      is_group: true,
      parent_account_name: "مدينون تجاريون",
    },
    {
      name: "عملاء عالم خارجي",
      account_number: 1615,
      is_group: true,
      parent_account_name: "مدينون تجاريون",
    },
    {
      name: "أوراق قبض قطاع اشتراكي",
      account_number: 1621,
      is_group: true,
      parent_account_name: "أوراق قبض",
    },
    {
      name: "أوراق قبض قطاع تعاوني",
      account_number: 1622,
      is_group: true,
      parent_account_name: "أوراق قبض",
    },
    {
      name: "أوراق قبض قطاع مختلط",
      account_number: 1623,
      is_group: true,
      parent_account_name: "أوراق قبض",
    },
    {
      name: "أوراق قبض قطاع خاص",
      account_number: 1624,
      is_group: true,
      parent_account_name: "أوراق قبض",
    },
    {
      name: "أوراق قبض عالم خارجي",
      account_number: 1625,
      is_group: true,
      parent_account_name: "أوراق قبض",
    },
    {
      name: "أوراق قبض برسم التحصيل",
      account_number: 1626,
      is_group: true,
      parent_account_name: "أوراق قبض",
    },
    {
      name: "حسابات جارية مدينة داخل المؤسسة",
      account_number: 1631,
      is_group: true,
      parent_account_name: "حسابات جارية مدينة",
    },
    {
      name: "حسابات جارية مدينة داخل المنشأة",
      account_number: 1632,
      is_group: true,
      parent_account_name: "حسابات جارية مدينة",
    },
    {
      name: "تامينات لدى الغير",
      account_number: 1661,
      is_group: true,
      parent_account_name: "حسابات مدينة متنوعة",
    },
    {
      name: "ايرادات مستحقة",
      account_number: 1662,
      is_group: true,
      parent_account_name: "حسابات مدينة متنوعة",
    },
    {
      name: "مصاريف مدفوعة مقدما",
      account_number: 1663,
      is_group: true,
      parent_account_name: "حسابات مدينة متنوعة",
    },
    {
      name: "طلبات التعويض",
      account_number: 1664,
      is_group: true,
      parent_account_name: "حسابات مدينة متنوعة",
    },
    {
      name: "فروقات نقدية ومخزنية",
      account_number: 1665,
      is_group: true,
      parent_account_name: "حسابات مدينة متنوعة",
    },
    {
      name: "سلف لأغراض النشاط",
      account_number: 1671,
      is_group: true,
      parent_account_name: "سلف",
    },
    {
      name: "سلف منتسبين",
      account_number: 1672,
      is_group: true,
      parent_account_name: "سلف",
    },
    {
      name: "سلف الزواج",
      account_number: 1673,
      is_group: true,
      parent_account_name: "سلف",
    },
    {
      name: "نقد في صندوق المركز",
      account_number: 1811,
      is_group: true,
      parent_account_name: "نقدية بالصندوق",
    },
    {
      name: "مصرف الرافدين",
      account_number: 1831,
      is_group: true,
      parent_account_name: "نقدية لدى المصارف",
    },
    {
      name: "مصرف الاسلامي",
      account_number: 1832,
      is_group: true,
      parent_account_name: "نقدية لدى المصارف",
    },
    {
      name: "شيكات وحوالات قيد التحصيل",
      account_number: 1851,
      is_group: true,
      parent_account_name: "صكوك وحوالات",
    },
    {
      name: "حوالات بالطريق",
      account_number: 1852,
      is_group: true,
      parent_account_name: "صكوك وحوالات",
    },
    {
      name: "شيكات وحوالات مرفوضة",
      account_number: 1853,
      is_group: true,
      parent_account_name: "صكوك وحوالات",
    },
    {
      name: "احتياطي التوسعات",
      account_number: 2211,
      is_group: true,
      parent_account_name: "احتياطي راسمالية",
    },
    {
      name: "احتياطي ارتفاع اسعار الموجودات الثابتة",
      account_number: 2212,
      is_group: true,
      parent_account_name: "احتياطي راسمالية",
    },
    {
      name: "احتياطي الزامي وقانوني",
      account_number: 2213,
      is_group: true,
      parent_account_name: "احتياطي راسمالية",
    },
    {
      name: "مخصص اندثار اراضي",
      account_number: 2311,
      is_group: true,
      parent_account_name: "مخصص الاندثار المتراكم",
    },
    {
      name: "مخصص اندثار مباني",
      account_number: 2312,
      is_group: true,
      parent_account_name: "مخصص الاندثار المتراكم",
    },
    {
      name: "مخصص اندثار الات ومعدات",
      account_number: 2313,
      is_group: true,
      parent_account_name: "مخصص الاندثار المتراكم",
    },
    {
      name: "مخصص اندثار وسائل نقل",
      account_number: 2314,
      is_group: true,
      parent_account_name: "مخصص الاندثار المتراكم",
    },
    {
      name: "مخصص اندثار قوالب وعدد",
      account_number: 2315,
      is_group: true,
      parent_account_name: "مخصص الاندثار المتراكم",
    },
    {
      name: "مخصص اندثار اثاث",
      account_number: 2316,
      is_group: true,
      parent_account_name: "مخصص الاندثار المتراكم",
    },
    {
      name: "قروض مستلمة طويلة الأجل من القطاع الاشتراكي",
      account_number: 2411,
      is_group: true,
      parent_account_name: "قروض مستلمة طويلة الأجل",
    },
    {
      name: "قروض مستلمة طويلة الأجل من القطاع التعاوني",
      account_number: 2412,
      is_group: true,
      parent_account_name: "قروض مستلمة طويلة الأجل",
    },
    {
      name: "قروض مستلمة طويلة الأجل من القطاع المختلط",
      account_number: 2413,
      is_group: true,
      parent_account_name: "قروض مستلمة طويلة الأجل",
    },
    {
      name: "قروض مستلمة طويلة الأجل من القطاع الخاص",
      account_number: 2414,
      is_group: true,
      parent_account_name: "قروض مستلمة طويلة الأجل",
    },
    {
      name: "قروض مستلمة طويلة الأجل من العالم الخارجي",
      account_number: 2415,
      is_group: true,
      parent_account_name: "قروض مستلمة طويلة الأجل",
    },
    {
      name: "قروض مستلمة قصيرة الأجل من القطاع الاشتراكي",
      account_number: 2421,
      is_group: true,
      parent_account_name: "قروض مستلمة قصيرة الأجل",
    },
    {
      name: "قروض مستلمة قصيرة الأجل من القطاع التعاوني",
      account_number: 2422,
      is_group: true,
      parent_account_name: "قروض مستلمة قصيرة الأجل",
    },
    {
      name: "قروض مستلمة قصيرة الأجل من القطاع المختلط",
      account_number: 2423,
      is_group: true,
      parent_account_name: "قروض مستلمة قصيرة الأجل",
    },
    {
      name: "قروض مستلمة قصيرة الأجل من القطاع الخاص",
      account_number: 2424,
      is_group: true,
      parent_account_name: "قروض مستلمة قصيرة الأجل",
    },
    {
      name: "قروض مستلمة قصيرة الأجل من العالم الخارجي",
      account_number: 2425,
      is_group: true,
      parent_account_name: "قروض مستلمة قصيرة الأجل",
    },
    {
      name: "مجهزون قطاع اشتراكي",
      account_number: 2611,
      is_group: true,
      parent_account_name: "المجهزون",
    },
    {
      name: "مجهزون قطاع تعاوني",
      account_number: 2612,
      is_group: true,
      parent_account_name: "المجهزون",
    },
    {
      name: "مجهزون قطاع مختلط",
      account_number: 2613,
      is_group: true,
      parent_account_name: "المجهزون",
    },
    {
      name: "مجهزون قطاع خاص",
      account_number: 2614,
      is_group: true,
      parent_account_name: "المجهزون",
    },
    {
      name: "مجهزون عالم خارجي",
      account_number: 2615,
      is_group: true,
      parent_account_name: "المجهزون",
    },
    {
      name: "اوراق دفع قطاع اشتراكي",
      account_number: 2621,
      is_group: true,
      parent_account_name: "أوراق دفع",
    },
    {
      name: "اوراق دفع قطاع تعاوني",
      account_number: 2622,
      is_group: true,
      parent_account_name: "أوراق دفع",
    },
    {
      name: "اوراق دفع قطاع مختلط",
      account_number: 2623,
      is_group: true,
      parent_account_name: "أوراق دفع",
    },
    {
      name: "اوراق دفع قطاع خاص",
      account_number: 2624,
      is_group: true,
      parent_account_name: "أوراق دفع",
    },
    {
      name: "اوراق دفع عالم خارجي",
      account_number: 2625,
      is_group: true,
      parent_account_name: "أوراق دفع",
    },
    {
      name: "حسابات جارية دائنة داخل المؤسسة",
      account_number: 2631,
      is_group: true,
      parent_account_name: "حسابات جارية دائنة",
    },
    {
      name: "حسابات جارية دائنة داخل المنشأة",
      account_number: 2632,
      is_group: true,
      parent_account_name: "حسابات جارية دائنة",
    },
    {
      name: "سلف مستلمة مقدما",
      account_number: 2641,
      is_group: true,
      parent_account_name: "حسابات التعهدات",
    },
    {
      name: "الذرعات المنجزة",
      account_number: 2642,
      is_group: true,
      parent_account_name: "حسابات التعهدات",
    },
    {
      name: "تأمينات مستلمة",
      account_number: 2661,
      is_group: true,
      parent_account_name: "دائرة الضمان الاجتماعي",
    },
    {
      name: "إيرادات مستلمة مقدما",
      account_number: 2662,
      is_group: true,
      parent_account_name: "دائرة الضمان الاجتماعي",
    },
    {
      name: "مصاريف مستحقة",
      account_number: 2663,
      is_group: true,
      parent_account_name: "دائرة الضمان الاجتماعي",
    },
    {
      name: "رواتب واجور مستحقة",
      account_number: 2664,
      is_group: true,
      parent_account_name: "دائرة الضمان الاجتماعي",
    },
    {
      name: "رواتب واجور معادة",
      account_number: 2665,
      is_group: true,
      parent_account_name: "دائرة الضمان الاجتماعي",
    },
    {
      name: "مديرية التقاعد العامة",
      account_number: 2666,
      is_group: true,
      parent_account_name: "دائرة الضمان الاجتماعي",
    },
    {
      name: "مؤسسة التقاعد والضمان الاجتماعي",
      account_number: 2667,
      is_group: true,
      parent_account_name: "دائرة الضمان الاجتماعي",
    },
    {
      name: "استقطاعات من المنتسبين لحسابات الغير",
      account_number: 2671,
      is_group: true,
      parent_account_name: "استقطاعات لحساب الغير",
    },
    {
      name: "استقطاعات من غير المنتسبين لحسابات الغير",
      account_number: 2672,
      is_group: true,
      parent_account_name: "استقطاعات لحساب الغير",
    },
    {
      name: "مقابل فرق الايجار المحتسب",
      account_number: 2941,
      is_group: true,
      parent_account_name: "حسابات النتيجة الدائنة",
    },
    {
      name: "مقابل فرق الفوائد المحتسبة",
      account_number: 2942,
      is_group: true,
      parent_account_name: "حسابات النتيجة الدائنة",
    },
    {
      name: "مقابل فرق تقويم لغير مخزن الانتاج التام",
      account_number: 2943,
      is_group: true,
      parent_account_name: "حسابات النتيجة الدائنة",
    },
    {
      name: "مقابل فرق تقويم لغير مخزون بضائع بغرض البيع",
      account_number: 2944,
      is_group: true,
      parent_account_name: "حسابات النتيجة الدائنة",
    },
    {
      name: "الراتب الاسمي",
      account_number: 3111,
      is_group: true,
      parent_account_name: "رواتب واجور الموظفين",
    },
    {
      name: "مخصصات ومكافئات تشجيعية",
      account_number: 3112,
      is_group: true,
      parent_account_name: "رواتب واجور الموظفين",
    },
    {
      name: "مخصصات نقل",
      account_number: 3113,
      is_group: true,
      parent_account_name: "رواتب واجور الموظفين",
    },
    {
      name: "مخصصات غلاء معيشة",
      account_number: 3114,
      is_group: true,
      parent_account_name: "رواتب واجور الموظفين",
    },
    {
      name: "مخصصات حيازة فنية وادارية وعمل اضافي",
      account_number: 3115,
      is_group: true,
      parent_account_name: "رواتب واجور الموظفين",
    },
    {
      name: "مخصصات حيازة",
      account_number: 3116,
      is_group: true,
      parent_account_name: "رواتب واجور الموظفين",
    },
    {
      name: "مخصصات زوجية واطفال",
      account_number: 3117,
      is_group: true,
      parent_account_name: "رواتب واجور الموظفين",
    },
    {
      name: "مخصصات شهادة",
      account_number: 3118,
      is_group: true,
      parent_account_name: "رواتب واجور الموظفين",
    },
    {
      name: "مخصصات اخرى",
      account_number: 3119,
      is_group: true,
      parent_account_name: "رواتب واجور الموظفين",
    },
    {
      name: "المحروقات",
      account_number: 3221,
      is_group: false,
      parent_account_name: "وقود وزيوت",
    },
    {
      name: "لوازم ومهمات",
      account_number: 3251,
      is_group: false,
      parent_account_name: "المتنوعات",
    },
    {
      name: "قرطاسية",
      account_number: 3252,
      is_group: false,
      parent_account_name: "المتنوعات",
    },
    {
      name: "كتب تعليمية",
      account_number: 3253,
      is_group: false,
      parent_account_name: "المتنوعات",
    },
    {
      name: "مخلفات ومستهلكات",
      account_number: 3254,
      is_group: false,
      parent_account_name: "المتنوعات",
    },
    {
      name: "صحف ومجلات",
      account_number: 3258,
      is_group: false,
      parent_account_name: "المتنوعات",
    },
    {
      name: "كساوي",
      account_number: 3261,
      is_group: false,
      parent_account_name: "تجهيزات العاملين",
    },
    {
      name: "مواد غذائية",
      account_number: 3262,
      is_group: false,
      parent_account_name: "تجهيزات العاملين",
    },
    {
      name: "مواد طبية",
      account_number: 3263,
      is_group: false,
      parent_account_name: "تجهيزات العاملين",
    },
    {
      name: "المياه",
      account_number: 3271,
      is_group: false,
      parent_account_name: "المياه والكهرباء",
    },
    {
      name: "الكهرباء",
      account_number: 3272,
      is_group: false,
      parent_account_name: "المياه والكهرباء",
    },
    {
      name: "صيانة مباني",
      account_number: 3312,
      is_group: false,
      parent_account_name: "خدمات الصيانة",
    },
    {
      name: "صيانة الات ومعدات",
      account_number: 3313,
      is_group: false,
      parent_account_name: "خدمات الصيانة",
    },
    {
      name: "صيانة وسائل نقل وانتقال",
      account_number: 3314,
      is_group: false,
      parent_account_name: "خدمات الصيانة",
    },
    {
      name: "صيانة عدد وقوالب",
      account_number: 3315,
      is_group: false,
      parent_account_name: "خدمات الصيانة",
    },
    {
      name: "صيانة أثاث واجهزة مكاتب وحاسبات",
      account_number: 3316,
      is_group: false,
      parent_account_name: "خدمات الصيانة",
    },
    {
      name: "صيانة تاسيسات كهرباء وماء",
      account_number: 3317,
      is_group: false,
      parent_account_name: "خدمات الصيانة",
    },
    {
      name: "دعاية واعلان ونشاطات",
      account_number: 3331,
      is_group: false,
      parent_account_name: "دعاية وطبع وضيافة",
    },
    {
      name: "نشر وطبع",
      account_number: 3332,
      is_group: false,
      parent_account_name: "دعاية وطبع وضيافة",
    },
    {
      name: "الضيافة",
      account_number: 3333,
      is_group: false,
      parent_account_name: "دعاية وطبع وضيافة",
    },
    {
      name: "مطبوعات اخرى",
      account_number: 3334,
      is_group: false,
      parent_account_name: "دعاية وطبع وضيافة",
    },
    {
      name: "نقل العاملين",
      account_number: 3341,
      is_group: false,
      parent_account_name: "نقل وايفاد واتصالات",
    },
    {
      name: "نقل السلع والبضائع",
      account_number: 3342,
      is_group: false,
      parent_account_name: "نقل وايفاد واتصالات",
    },
    {
      name: "السفروالايفاد",
      account_number: 3343,
      is_group: false,
      parent_account_name: "نقل وايفاد واتصالات",
    },
    {
      name: "اتصالات عامة/ وانترنيت",
      account_number: 3344,
      is_group: false,
      parent_account_name: "نقل وايفاد واتصالات",
    },
    {
      name: "استئجار مباني وانشاءات",
      account_number: 3352,
      is_group: false,
      parent_account_name: "استئجار موجودات ثابتة",
    },
    {
      name: "استئجار الآت ومعدات",
      account_number: 3353,
      is_group: false,
      parent_account_name: "استئجار موجودات ثابتة",
    },
    {
      name: "استئجار وسائط نقل وانتقال",
      account_number: 3354,
      is_group: false,
      parent_account_name: "استئجار موجودات ثابتة",
    },
    {
      name: "استئجار عدد وقوالب",
      account_number: 3355,
      is_group: false,
      parent_account_name: "استئجار موجودات ثابتة",
    },
    {
      name: "استئجار اثاث واجهزة مكاتب",
      account_number: 3356,
      is_group: false,
      parent_account_name: "استئجار موجودات ثابتة",
    },
    {
      name: "اشتراكات وانتماءات",
      account_number: 3361,
      is_group: false,
      parent_account_name: "مصروفات خدمية متنوعة",
    },
    {
      name: "اقساط التامين",
      account_number: 3362,
      is_group: false,
      parent_account_name: "مصروفات خدمية متنوعة",
    },
    {
      name: "مكافأت لغير العاملين عن خدمات مؤداة",
      account_number: 3363,
      is_group: false,
      parent_account_name: "مصروفات خدمية متنوعة",
    },
    {
      name: "ضرائب ورسوم مدفوعه لجهات اجنبية",
      account_number: 3364,
      is_group: false,
      parent_account_name: "مصروفات خدمية متنوعة",
    },
    {
      name: "خدمات قانونية",
      account_number: 3365,
      is_group: false,
      parent_account_name: "مصروفات خدمية متنوعة",
    },
    {
      name: "خدمات مصرفية",
      account_number: 3366,
      is_group: false,
      parent_account_name: "مصروفات خدمية متنوعة",
    },
    {
      name: "تدريب وتأهيل",
      account_number: 3367,
      is_group: false,
      parent_account_name: "مصروفات خدمية متنوعة",
    },
    {
      name: "مصروفات خدمية أخرى",
      account_number: 3369,
      is_group: false,
      parent_account_name: "مصروفات خدمية متنوعة",
    },
    {
      name: "رواتب تقاعدية",
      account_number: 3811,
      is_group: true,
      parent_account_name: "نفقات التقاعد والضمان الاجتماعي",
    },
    {
      name: "مكافءات اجتماعيه وتشجيعية",
      account_number: 3812,
      is_group: true,
      parent_account_name: "نفقات التقاعد والضمان الاجتماعي",
    },
    {
      name: "تبرعات للغير",
      account_number: 3831,
      is_group: false,
      parent_account_name: "مصروقات تحويلية متنوعة",
    },
    {
      name: "تعويضات وغرامات",
      account_number: 3832,
      is_group: false,
      parent_account_name: "مصروقات تحويلية متنوعة",
    },
    {
      name: "ديون مشطوبة",
      account_number: 3833,
      is_group: false,
      parent_account_name: "مصروقات تحويلية متنوعة",
    },
    {
      name: "نفقات خدمات خاصة",
      account_number: 3834,
      is_group: false,
      parent_account_name: "مصروقات تحويلية متنوعة",
    },
    {
      name: "اطفاء سلف الزواج",
      account_number: 3835,
      is_group: false,
      parent_account_name: "مصروقات تحويلية متنوعة",
    },
    {
      name: "حصة المنشاة في تمويل المؤسسة العامة",
      account_number: 3836,
      is_group: false,
      parent_account_name: "مصروقات تحويلية متنوعة",
    },
    {
      name: "رسوم انتاج",
      account_number: 3841,
      is_group: false,
      parent_account_name: "ضرائب ورسوم رئيسي",
    },
    {
      name: "ضرائب ورسوم",
      account_number: 3842,
      is_group: false,
      parent_account_name: "ضرائب ورسوم رئيسي",
    },
    {
      name: "اعانات داخلية",
      account_number: 3851,
      is_group: false,
      parent_account_name: "اعانات",
    },
    {
      name: "اعانات خارجية",
      account_number: 3852,
      is_group: false,
      parent_account_name: "اعانات",
    },
    {
      name: "مساهمة التقاعد والضمان الاجتماعي",
      account_number: 4811,
      is_group: false,
      parent_account_name: "الإيرادات التحويلية",
    },
    {
      name: "حصة الضمان من ارباح المنشأت",
      account_number: 4812,
      is_group: false,
      parent_account_name: "الإيرادات التحويلية",
    },
    {
      name: "منح الخزينة العامة",
      account_number: 4821,
      is_group: false,
      parent_account_name: "الإيرادات التحويلية",
    },
    {
      name: "منح الوحدات المركزية أو التابعة",
      account_number: 4822,
      is_group: false,
      parent_account_name: "الإيرادات التحويلية",
    },
    {
      name: "تبرعات مستلمة",
      account_number: 4831,
      is_group: false,
      parent_account_name: "الإيرادات التحويلية",
    },
    {
      name: "تعوسضات وغرامات",
      account_number: 4832,
      is_group: false,
      parent_account_name: "الإيرادات التحويلية",
    },
    {
      name: "ديون سبق شطبها",
      account_number: 4833,
      is_group: false,
      parent_account_name: "الإيرادات التحويلية",
    },
    {
      name: "كلفة شراء أراضي زراعية",
      account_number: 11111,
      is_group: true,
      parent_account_name: "اراضي",
    },
    {
      name: "كلفة استصلاح أراضي زراعية",
      account_number: 11112,
      is_group: true,
      parent_account_name: "اراضي",
    },
    {
      name: "آبار",
      account_number: 11241,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "مناجم",
      account_number: 11242,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "مقالع",
      account_number: 11243,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "خطوط السكك الحديدية",
      account_number: 11281,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "ارصفة الموانئ والمراسي",
      account_number: 11282,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "مدارج المطارات",
      account_number: 11283,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "مجاري المياه الثقيلة",
      account_number: 11291,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "احوض مائية",
      account_number: 11292,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "بيوت زجاجية",
      account_number: 11293,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "خطوط انابيب الماء",
      account_number: 11294,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "خطوط الكهرباء والهاتف",
      account_number: 11295,
      is_group: true,
      parent_account_name: "مباني وانشاءات",
    },
    {
      name: "وسائل نقل الركاب",
      account_number: 11411,
      is_group: true,
      parent_account_name: "وسائل نقل وأنتقال",
    },
    {
      name: "وسائل نقل البضائع",
      account_number: 11412,
      is_group: true,
      parent_account_name: "وسائل نقل وأنتقال",
    },
    {
      name: "عربات نقل اخرى",
      account_number: 11413,
      is_group: true,
      parent_account_name: "وسائل نقل وأنتقال",
    },
    {
      name: "اجور تنظيم الحسابات",
      account_number: 33681,
      is_group: false,
      parent_account_name: "مصروفات خدمية متنوعة",
    },
    {
      name: "اجور تدقيق الحسابات",
      account_number: 33682,
      is_group: false,
      parent_account_name: "مصروفات خدمية متنوعة",
    },
  ];
}

function getCurrencies(): Array<Currency> {
  return [
    {
      name: "IQD",
      exchange_rate: 1,
      selling_rate: null,
      buying_rate: null,
      min_selling_rate: null,
      max_buying_rate: null,
      currency_symbol: "د.ع",
    },
    {
      name: "USD",
      exchange_rate: 1.2,
      selling_rate: null,
      buying_rate: null,
      min_selling_rate: null,
      max_buying_rate: null,
      currency_symbol: "$",
    },
  ];
}
